project: 
  type: website
  output-dir: docs

website:
  title: "Aylla Ermland Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/starter-analysis-exercise.html
          - text: "READy Exercise"
            file: ready-exercise/ready-exercise.html
          - text: "Data Exercise"
            file: data-exercise/data-exercise.html
          - text: "Data Analysis Exercise"
            file: cdcdata-exercise/cdcdata-exercise.html
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.html
          - text: "Fitting Exercise"
            file: fitting-exercise/fitting-exercise.html
          - text: "Ml Models Exercise"
            file: ml-models-exercise/ml-models-exercise.qmd
          - text: "Tidy Tuesday Exercise"
            file: tidytuesday-exercise/tidytuesday-exercise.html
    right:
      - icon: github 
        href: https://github.com/ayllae/AyllaErmland-portfolio       
format:
  html:
    theme: cosmo
    highlight: zenburn
    css: styles.css
    toc: FALSE